import type { Projeto } from './types'

export const PROJETOS: Projeto[] = [
  {
    id: 1,
    codigo: 'PRJ-0042',
    cliente: 'Helena Moretti',
    ambiente: 'Cozinha planejada',
    projetista: 'Marina Alves',
    etapa: 'producao',
    valor: 42800,
    software: 'Promob',
    versao: 3,
    aprovado: true,
    atualizadoEm: '2026-06-16T14:20:00',
    versoes: [
      { numero: 3, data: '2026-06-16T14:20:00', autor: 'Marina Alves', resumo: 'Ajuste de torre quente e puxadores' },
      { numero: 2, data: '2026-06-10T09:10:00', autor: 'Marina Alves', resumo: 'Inclusão de cooktop e coifa' },
      { numero: 1, data: '2026-06-02T16:40:00', autor: 'Marina Alves', resumo: 'Versão inicial importada do Promob' },
    ],
    pecas: [
      { nome: 'Módulo aéreo 800mm', acabamento: 'MDF Branco TX', qtd: 3 },
      { nome: 'Módulo base 600mm', acabamento: 'MDF Carvalho', qtd: 4 },
      { nome: 'Torre quente', acabamento: 'MDF Branco TX', qtd: 1 },
      { nome: 'Puxador perfil', acabamento: 'Alumínio', qtd: 12 },
    ],
  },
  {
    id: 2,
    codigo: 'PRJ-0043',
    cliente: 'Construtora Vega',
    ambiente: 'Home office (12 un.)',
    projetista: 'Carlos Dias',
    etapa: 'tecnico',
    valor: 158200,
    software: 'Gabster',
    versao: 2,
    aprovado: false,
    atualizadoEm: '2026-06-17T08:05:00',
    versoes: [
      { numero: 2, data: '2026-06-17T08:05:00', autor: 'Carlos Dias', resumo: 'Padronização de gaveteiros' },
      { numero: 1, data: '2026-06-12T11:00:00', autor: 'Carlos Dias', resumo: 'Versão inicial (12 unidades)' },
    ],
    pecas: [
      { nome: 'Mesa em L 1600mm', acabamento: 'MDF Cinza', qtd: 12 },
      { nome: 'Gaveteiro 3 gavetas', acabamento: 'MDF Cinza', qtd: 12 },
    ],
  },
  {
    id: 3,
    codigo: 'PRJ-0044',
    cliente: 'Rafael Nunes',
    ambiente: 'Dormitório casal',
    projetista: 'Marina Alves',
    etapa: 'montagem',
    valor: 23400,
    software: 'Promob',
    versao: 1,
    aprovado: true,
    atualizadoEm: '2026-06-15T17:30:00',
    versoes: [
      { numero: 1, data: '2026-06-05T10:00:00', autor: 'Marina Alves', resumo: 'Versão inicial aprovada' },
    ],
    pecas: [
      { nome: 'Guarda-roupa 6 portas', acabamento: 'MDF Freijó', qtd: 1 },
      { nome: 'Cabeceira estofada', acabamento: 'Linho Bege', qtd: 1 },
    ],
  },
  {
    id: 4,
    codigo: 'PRJ-0045',
    cliente: 'Ana Beatriz',
    ambiente: 'Closet + banheiro',
    projetista: 'Rui Pena',
    etapa: 'medicao',
    valor: 67900,
    software: 'Dinabox',
    versao: 1,
    aprovado: false,
    atualizadoEm: '2026-06-14T13:15:00',
    versoes: [
      { numero: 1, data: '2026-06-14T13:15:00', autor: 'Rui Pena', resumo: 'Versão inicial — aguardando medição' },
    ],
    pecas: [{ nome: 'Closet aramado', acabamento: 'Alumínio', qtd: 1 }],
  },
  {
    id: 5,
    codigo: 'PRJ-0046',
    cliente: 'Studio Lume',
    ambiente: 'Recepção comercial',
    projetista: 'Carlos Dias',
    etapa: 'projeto',
    valor: 51300,
    software: 'SketchUp + plugin',
    versao: 1,
    aprovado: false,
    atualizadoEm: '2026-06-17T10:40:00',
    versoes: [
      { numero: 1, data: '2026-06-17T10:40:00', autor: 'Carlos Dias', resumo: 'Rascunho inicial' },
    ],
    pecas: [],
  },
]

export const PROJETISTAS = ['Marina Alves', 'Carlos Dias', 'Rui Pena']
